### PR TITLE
fix(scylla_manager): Added a provider to the agent's s3 config

### PR DESCRIPTION
**Pull request by ShlomiBalalis**
### **BACKPORT TO MANAGER_2.0**

### CODE REVIEW

**Comment by roydahan** [comment]
Please add body message to the commit explain what is provider and why we need it now.
What is the issue it's trying to fix.

**Comment by ShlomiBalalis** [comment]
> Please add body message to the commit explain what is provider and why we need it now.
> What is the issue it's trying to fix.

Done

**Comment by roydahan** [comment]
@ShlomiBalalis when merged to master and pass, let me know so I can backport.

**Comment by ShlomiBalalis** [comment]
@roydahan Actually right now branch 2.0 does not require it yet. It actually causes the manager to fail, so for now we'll leave it be.

**Comment by ShlomiBalalis** [comment]
@roydahan @fruch It is now required on 2.0, can you please backport?

**Comment by roydahan** [comment]
backported.

**Pull request merged**
