### PR TITLE
ccmlib/utils: add inotify wrapper

### PR DESCRIPTION
**Pull request by tchaikov**
a typical session looks like:

```console
$ while true; do
    sleep 1
    echo 1 >> /tmp/foobar
  done
```

in the meanwhile:

```py
from inotify import INotify, Flag

notify = INotify()
with notify.watch("/tmp/foobar", Flag.MODIFY):
  for e in notify.read():
    print(e)
```

### CODE REVIEW

**Comment by tchaikov** [comment]
inspired by #577

**Comment by fruch** [comment]
@tchaikov 

can you add a test, or some example of usage for this, it's not exactly clear what exactly do we need it for...

for using in polling log files ?

**Comment by tchaikov** [comment]
> @tchaikov
> 
> can you add a test, or some example of usage for this, it's not exactly clear what exactly do we need it for...

indeed. will do.

> 
> for using in polling log files ?

yes, it's exactly the intended use case.

**Comment by tchaikov** [comment]
v2:

- added tests for inotify wrapper.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@tchaikov 

I'll merge it once tests pass

anyhow with the next steam, we need to be careful, and make sure we run all tests (all variant, and enterprise)
since it something that affect all of the tests

**Comment by tchaikov** [comment]
> need to be careful with type annotations, we still support python 3.8 (cause of usage in drivers)
> 
> ```
> tests/test_utils_inotify.py:1: in <module>
>     from ccmlib.utils.inotify import INotify, Flag
> ccmlib/utils/inotify.py:71: in <module>
>     class Event:
> ccmlib/utils/inotify.py:74: in Event
>     flags: list[Flag]
> E   TypeError: 'type' object is not subscriptable
> ```

ack.

**Comment by tchaikov** [comment]
v2:

- use typing annotations compatible with Python 3.8

**Comment by nyh** [comment]
> > for using in polling log files ?
> 
> yes, it's exactly the intended use case.

Inotify is useful when you have a lot of files, and not sure when any of them will change - it's possible that a file will change in the next second, or maybe it won't change in a year. This isn't usually the case in log files - you have just one or a small number of those (one per node), and usually each of them changes all the time (our logs are very chattery). So we need to constantly read from each of them looking if the log message we cared about appeared.

Moreover in a modern machine, code which looks like:

```
while True:
   check_the_end_of_the_log()
   sleep(0.1)
```
Is very efficient (there is a file system cache) and doesn't really needs optimization.

Can you give an example of a problem - usability or performance problem - that you're trying to solve?

**Comment by fruch** [comment]
> > > for using in polling log files ?
> > 
> > 
> > yes, it's exactly the intended use case.
> 
> Inotify is useful when you have a lot of files, and not sure when any of them will change - it's possible that a file will change in the next second, or maybe it won't change in a year. This isn't usually the case in log files - you have just one or a small number of those (one per node), and usually each of them changes all the time (our logs are very chattery). So we need to constantly read from each of them looking if the log message we cared about appeared.
> 
> Moreover in a modern machine, code which looks like:
> 
> ```
> while True:
>    check_the_end_of_the_log()
>    sleep(0.1)
> ```
> 
> Is very efficient (there is a file system cache) and doesn't really needs optimization.
> 
> Can you give an example of a problem - usability or performance problem - that you're trying to solve?

I think the issue at hand was the the loop we have was doing that loop with sleeps which were hardcoded
and were too big for on specific test, now those times can be configured.

I think @tchaikov is aiming into something, that would need those sleeps at all. 
I don't think we were having performance issue at hand, or having big amount of files to be watched

but yes, might be a bit of an overkill.
also, we should be think/moving to ways to test things with depending on the logs output. and maybe no entrancing more into it.
so far we did succeeded much in it, and every boot has a mix flavor of using API calls and waiting for logs, for all bunch of compatibility reasons.

**Comment by tchaikov** [comment]
@fruch @nyh do we have any objections? this PR was approved. and i made changes per the request of reviewer.

**Comment by fruch** [comment]
> @fruch @nyh do we have any objections? this PR was approved. and i made changes per the request of reviewer. 

There is still the concern it might be an overkill 

But I'm willing to experiment on how it would be used and as said , we'll need to run all of the tests to validate

**Comment by nyh** [comment]
> I think the issue at hand was the the loop we have was doing that loop with sleeps which were hardcoded and were too big for on specific test, now those times can be configured.

Sleeps are a problem in a lot of dtests, but it has nothing to do with **logs**. As I mentioned, because we enable a lot of crap in our log, our logs constantly get written, so inotify will return almost immediately anyway. If we use sleep(0.1) when looking at logs, that would have been good enough - nobody would have complained the sleep was too short or too long. I think inotify is a complete overkill for this use case. But I guess it's not wrong.

On the other hand, sleep in log searching is good if you iteratively keep reading from the **same** mark (and not always read just the new data from the last read). In that case, waking up every millisecond and reading all the data from the original mark is a big waste. If we expect the message to appear only after 5 seconds (usually), then sleeping 5 seconds and then checking is much more efficient. Of course even better is to read in every iteration just from the end of the previous iteration. But this must be done carefully (you need to at least cut the log on full lines and not in the middle of a line), and I don't know if we're careful in that. @fruch maybe you know.

**Comment by fruch** [comment]
@nyh 

All is correct, but someone did complain about 0.1 sleep is too long, for some use case, and we introduced a way to lower it down for that specific test.

That thread ignited @tchaikov direction here.

As I've said I'm o.k. to give it a try, it might prove useful in more place.

Nowadays we have quite good ways to test such a thing with all tests, i.e. we have quite stright criteria for such a change (that all tests pass :))

**Pull request merged**
