### PR TITLE
Revert "fix(scylla_node): covering cases when network_interaces records could be None"

### PR DESCRIPTION
**Pull request by fruch**
This reverts commit 811bf0c424b2b50145c29e7605341882a3ac5954.

### CODE REVIEW

**Review by dkropachev — COMMENTED** [review]
LGTM

**Review by dkropachev — APPROVED** [review]

**Comment by bhalevy** [comment]
What is the motivation for doing so?

**Review by bhalevy — APPROVED** [review]
OK, so just to tie the loose ends, it's reverted because of a regression reported in https://github.com/scylladb/scylla-dtest/issues/1965

**Comment by bhalevy** [comment]
@fruch ping

**Comment by bhalevy** [comment]
@fruch ping

**Pull request merged**
