### PR TITLE
treewide: use yaml.load(f, Loader=yaml.FullLoader)

### LINKED ISSUE #142: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated
See for example [byo_build_tests_dtest/70/consoleFull](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/70/consoleFull):
```
18:31:43 /jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/scylla-ccm/ccmlib/scylla_node.py:601: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
18:31:43   data = yaml.load(f)
18:31:43 /jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/scylla-ccm/ccmlib/scylla_node.py:324: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

Please read [https://msg.pyyaml.org/load](https://msg.pyyaml.org/load) for full details.

### PR DESCRIPTION
**Pull request by bhalevy**
Address following warning:
    YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

Please read https://msg.pyyaml.org/load for full details.

Fixes #142

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
Fixed AttributeError issue by catching the respective exception and defaulting to the exiting call

**Comment by bhalevy** [comment]
Successful test run here: [http://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/337](http://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/337)

**Comment by bhalevy** [comment]
Ref #143

**Comment by roydahan** [comment]
@bhalevy can we close this one?
I see that we now use safe_load which conflicts with this one.

**Comment by bhalevy** [comment]
> @bhalevy can we close this one?
> I see that we now use safe_load which conflicts with this one.

yes, no problem

**Pull request closed without merging**
