### PR TITLE
scylla_node: ignore scylla-tools config files if scylla-tools is missing

### LINKED ISSUE #617: ccmlib should work when scylla-tools not installed
The issue is bit like https://github.com/scylladb/scylla-cluster-tests/issues/8799 and related with https://github.com/scylladb/scylladb/pull/20740, we are removing scylla-tools from default installation (and we will completely drop scylla-tools later).

But when I tested a PR to drop scylla-tools from unified package, dtest failed with:
```
21:44:43  Traceback (most recent call last):
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/bin/ccm", line 74, in <module>
21:44:43      cmd.run()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cmds/cluster_cmds.py", line 269, in run
21:44:43      cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 327, in populate
21:44:43      self.new_node(i, debug=debug, initial_token=tk, data_center=dc, rack=rack)
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 334, in new_node
21:44:43      node = self.create_node(name=f'node{i}',
21:44:43             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_cluster.py", line 93, in create_node
21:44:43      return ScyllaNode(name, self, auto_bootstrap, None,
21:44:43             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 51, in __init__
21:44:43      super().__init__(name, cluster, auto_bootstrap,
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/node.py", line 126, in __init__
21:44:43      self.import_config_files()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 975, in import_config_files
21:44:43      self.copy_config_files()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 981, in copy_config_files
21:44:43      conf_pattern = os.path.join(self.get_tools_java_dir(), 'conf', "jvm*.options")
21:44:43                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "<frozen posixpath>", line 76, in join
21:44:43  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Seems like ccmlib/scylla_node.py is not allowed to remove scylla-tools directory, but we need to do so.

### PR DESCRIPTION
**Pull request by tchaikov**
this change is created in the same spirit of 3a886404, so that we don't assume the existence of scylla-tools. otherwise we could have following failure:

```
07:51:05  Traceback (most recent call last):
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/bin/ccm", line 74, in <module>
07:51:05      cmd.run()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cmds/cluster_cmds.py", line 269, in run
07:51:05      cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 330, in populate
07:51:05      self.new_node(i, debug=debug, initial_token=tk, data_center=dc, rack=rack)
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 337, in new_node
07:51:05      node = self.create_node(name=f'node{i}',
07:51:05             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_cluster.py", line 94, in create_node
07:51:05      return ScyllaNode(name, self, auto_bootstrap, None,
07:51:05             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 53, in __init__
07:51:05      super().__init__(name, cluster, auto_bootstrap,
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/node.py", line 128, in __init__
07:51:05      self.import_config_files()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 979, in import_config_files
07:51:05      self.__copy_logback_files()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 1003, in __copy_logback_files
07:51:05      shutil.copy(os.path.join(self.get_tools_java_dir(), 'conf', 'logback-tools.xml'),
```

Fixes #617
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
- [ ] testing with `syuu1228/scylla.git:drop_tools_from_unified_package`: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2505/
- [ ] testing without this branch: https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/gating-dtest-release-with-consistent-topology-changes/147/

**Comment by tchaikov** [comment]
@fruch @syuu1228 @yaronkaikov hii everyone, i'd appreciate a review of this change. There are still failing tests in the [Jenkins build](https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2507/) however, I believe this change addresses some aspects of the issue and brings us closer to resolving the failing tests.

**Comment by fruch** [comment]
> @fruch @syuu1228 @yaronkaikov hii everyone, i'd appreciate a review of this change. There are still failing tests in the [Jenkins build](https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2507/) . however, I believe this change addresses some aspects of the issue and brings us closer to resolving the failing tests.

we are still left with ~500 tests failing with that removal change.
merging this one doesn't really get https://github.com/scylladb/scylla-cluster-tests/issues/8799 and closer to being finalized

**Comment by tchaikov** [comment]
as you put, there are two issues. 

- we assume the existence of scylla-tools. this is tracked by #617
- we do not use the native nodetool or the native alternatives are missing. this is tracked by https://github.com/scylladb/scylla-cluster-tests/issues/8799

but i i don't think the later is a dependency of the fix of #617.

**Comment by fruch** [comment]
> as you put, there are two issues.
> 
> * we assume the existence of scylla-tools. this is tracked by [ccmlib should work when scylla-tools not installed #617](https://github.com/scylladb/scylla-ccm/issues/617)
> * we do not use the native nodetool or the native alternatives are missing. this is tracked by [nonroot tests should call native nodetool scylla-cluster-tests#8799](https://github.com/scylladb/scylla-cluster-tests/issues/8799)
> 
> but i i don't think the later is a dependency of the fix of #617.

it was a mistake copying the wrong item https://github.com/scylladb/scylladb/pull/20740 is still breaking 500 dtests, so having this in doesn't address all of those.

**Comment by tchaikov** [comment]
fair enough. i explained this change does not address all of them.

**Comment by fruch** [comment]
> fair enough. i explained this change does not address all of them.

I don't know if we should give it up, but we are probably gonna have more changes needed for this effort.

**Comment by tchaikov** [comment]
> > fair enough. i explained this change does not address all of them.
> 
> I don't know if we should give it up, but we are probably gonna have more changes needed for this effort.

i asked for review , and explained why this change should be included. but failed to get the review or the acknowledgment or any comment regarding this PR. what i have is 

> having this in doesn't address all of those.

in my opinion, it's was a "NO". and it was not constructive. so i didn't what else i can do.

**Comment by fruch** [comment]
> > > fair enough. i explained this change does not address all of them.
> > 
> > I don't know if we should give it up, but we are probably gonna have more changes needed for this effort.
> 
> i asked for review , and explained why this change should be included. but failed to get the review or the acknowledgment or any comment regarding the change made in this PR, so that i could improve it. what i have is 
> 
> > having this in doesn't address all of those.
> 
> in my opinion, it's was a "NO". and it was not constructive. so i didn't know what else i can do, but to close it.

You got a review, and a question about it. not the review you wanted.

My concern is putting in multiple changes that we can't later track for backporting into pushing forward a change that can't be merged.

I.e. that doesn't seem to be the last of it, if there are 500 failing tests.

**Comment by tchaikov** [comment]
@fruch what was the question? i read all your comments again. but cannot find a question.

**Comment by fruch** [comment]
> @fruch what was the question? i am confused. i read all your comments again. but cannot find a question. and if you have concern on tracking multiple changes. how is it related to the change i proposed? i never claim that this change is the last one. but i wanted to limit the scope of a certain change.


https://github.com/scylladb/scylla-ccm/pull/618

Was to limit the scope as well wasn't it, but was solving all of what it's intended.

If there are changes needed for a PR to come into scylla, I would rather collect all what is required from one repo or other, then have a long long list of small changes.

Regardless, at any point I didn't decline this PR, I was asking questions, even if you didn't find the question marks.

**Comment by roydahan** [comment]
It seems like this PR is a step in the correct direction.
Most (or even all) of the failing tests are failing for 3 main tools that are missing:
- sstableloader
- sstabledump
- cqlsh (which shouldn't be taken from scylla-tools anyway).

**Comment by fruch** [comment]
also look like the cqlsh related tests were missing cause of of using `os.path.join` with None, and this should fix it:

```diff
diff --git a/ccmlib/scylla_node.py b/ccmlib/scylla_node.py
index 96fc5d6..7627c4b 100644
--- a/ccmlib/scylla_node.py
+++ b/ccmlib/scylla_node.py
@@ -153,9 +153,9 @@ class ScyllaNode(Node):
             os.path.join(self.node_install_dir, 'share', 'cassandra', BIN_DIR),
             os.path.join(self.get_cqlsh_dir(), BIN_DIR),
         ]
-        tools_java_dir = os.path.join(self.get_tools_java_dir(), BIN_DIR),
+        tools_java_dir = self.get_tools_java_dir()
         if tools_java_dir:
-            candidate_dirs.append(tools_java_dir)
+            candidate_dirs.append( os.path.join(tools_java_dir, BIN_DIR))
         for candidate_dir in candidate_dirs:
             candidate = shutil.which(toolname, path=candidate_dir)
             if candidate:
```

**Comment by roydahan** [comment]
@tchaikov Can you please resubmit this PR?
I think it's needed.

**Comment by tchaikov** [comment]
> @tchaikov Can you please resubmit this PR? I think it's needed.

@roydahan hi Roy, reopened.

**Comment by fruch** [comment]
> also look like the cqlsh related tests were missing cause of of using `os.path.join` with None, and this should fix it:
> 
> ```diff
> diff --git a/ccmlib/scylla_node.py b/ccmlib/scylla_node.py
> index 96fc5d6..7627c4b 100644
> --- a/ccmlib/scylla_node.py
> +++ b/ccmlib/scylla_node.py
> @@ -153,9 +153,9 @@ class ScyllaNode(Node):
>              os.path.join(self.node_install_dir, 'share', 'cassandra', BIN_DIR),
>              os.path.join(self.get_cqlsh_dir(), BIN_DIR),
>          ]
> -        tools_java_dir = os.path.join(self.get_tools_java_dir(), BIN_DIR),
> +        tools_java_dir = self.get_tools_java_dir()
>          if tools_java_dir:
> -            candidate_dirs.append(tools_java_dir)
> +            candidate_dirs.append( os.path.join(tools_java_dir, BIN_DIR))
>          for candidate_dir in candidate_dirs:
>              candidate = shutil.which(toolname, path=candidate_dir)
>              if candidate:
> ```
> 

@tchaikov check this part, I think it's missing for cqlsh related tests to work

**Comment by tchaikov** [comment]
> ```diff
> tools_java_dir = self.get_tools_java_dir()
> ```

incorporated.

**Comment by fruch** [comment]
@syuu1228 want to take it for a ride with you PR ?

**Comment by fruch** [comment]
taking it for a ride with master dtest/scylla:
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/605/ (Gossip - OSS)
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/606/ (Gossip - Enterprise)
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/607/ (Raft - OSS)
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/608/ (Raft - Enterprise)
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/609/ (Tablets - OSS)
- [ ] :clock1: https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/610/ (Tablets - Enterprise)

**Comment by fruch** [comment]
running one part again:
- [ ] 🕐 https://jenkins.scylladb.com/job/scylla-staging/job/dtest-pytest-gating/611/

**Review by fruch — APPROVED** [review]
LGTM

and passed the gating dtests

**Pull request merged**
