### PR TITLE
Use IPs instead of localhost for nodetool commands

### PR DESCRIPTION
**Pull request by tarzanek**
ONLY for scylla instances

reiteration of https://github.com/scylladb/scylla-ccm/pull/170
but now with cassandra instances in mind

### CODE REVIEW

**Comment by tarzanek** [comment]
@bhalevy @fruch what tests should I run locally so you would accept this patch?
I guess if I won't break anything, this patch will be allowed, or are there more conditions?

**Comment by bhalevy** [comment]
> @bhalevy @fruch what tests should I run locally so you would accept this patch?
> I guess if I won't break anything, this patch will be allowed, or are there more conditions?

@tarzanek you can run `CASSANDRA_DIR=../scylla/build/dev NOSE_PROCESSES=1 nosetests -s -v --process-timeout=1800 migration_test:TTLWithMigrate.big_table_with_ttls_test nodetool_additional_test:TestNodetool.cfstats_test`

**Comment by tarzanek** [comment]
Benny @bhalevy  check https://github.com/scylladb/scylla-ccm/issues/174
I already run that, that works with this patch :-)

**Comment by tarzanek** [comment]
```
% bg:0 Wed Sep 18,14:47 taz@tublat:~/git/_dtest_clean/scylla-dtest
➜  scylla-dtest git:(next) CASSANDRA_DIR=../scylla/build/release NOSE_PROCESSES=1 nosetests -s -v --process-timeout=1800 migration_test:TTLWithMigrate.big_table_with_ttls_test nodetool_addit
ional_test:TestNodetool.cfstats_test
running
['/home/taz/.dtest/dtest-plAuqY/test/node1/data/ks/cf-a3c69dc0da1211e98e25000000000000/mc-33-big-Data.db']
-- mc-33-big-Data.db -----

(EE)  (EE)  [node1 ERROR] OpenJDK 64-Bit Server VM warning: Cannot open file /home/taz/.ccm/repository/3.11.3/logs/gc.log due to No such file or directory
[node3 ERROR] OpenJDK 64-Bit Server VM warning: Cannot open file /home/taz/.ccm/repository/3.11.3/logs/gc.log due to No such file or directory
[node2 ERROR] OpenJDK 64-Bit Server VM warning: Cannot open file /home/taz/.ccm/repository/3.11.3/logs/gc.log due to No such file or directory
[node4 ERROR] OpenJDK 64-Bit Server VM warning: Cannot open file /home/taz/.ccm/repository/3.11.3/logs/gc.log due to No such file or directory
(EE)  running
['/home/taz/.dtest/dtest-EpoLuu/test/node1/data/ks/cf-01037b70da1311e9bea87b2996a7d701/mc-1-big-Data.db', '/home/taz/.dtest/dtest-EpoLuu/test/node1/data/ks/cf-01037b70da1311e9bea87b2996a7d70
1/mc-2-big-Data.db']
-- mc-1-big-Data.db -----
Cannot find file /home/taz/.dtest/dtest-EpoLuu/test/node1/data/ks/cf-01037b70da1311e9bea87b2996a7d701/mc-1-big-Data.db

-- mc-2-big-Data.db -----

big_table_with_ttls_test (migration_test.TTLWithMigrate) ... ok
cfstats_test (nodetool_additional_test.TestNodetool) ... ok

----------------------------------------------------------------------
Ran 2 tests in 344.366s

OK
```
works with this same patch

**Comment by bhalevy** [comment]
Note that scylladb/scylla-dtest#1110 adds `big_table_with_ttls_test` to next-gating tests

**Pull request merged**
