### PR TITLE
scylla_node: do_stop: ignore node.is_running

### LINKED ISSUE #309: scylla_node do_stop does not stop scylla_jmx if the scylla node is not running
See https://github.com/scylladb/scylla-ccm/issues/303#issuecomment-780443426

`do_stop` checks first if `self.is_running()` which will return false if the node exited already, e.g.  on error.
In this case we still need to stop/kill scylla_jmx, otherwise it stays up, holding jmx listen port.

From example:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/745/artifact/logs-release.2/dtest.log
```
2021-02-16 11:13:14,540 30123   ccm                            DEBUG    | node2: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-6rchw__r/test/node2/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-6rchw__r/test/node2/conf/s
cylla.yaml', '--log-to-stdout', '1', '--api-address', '127.0.61.2', '--collectd-hostname', '76836c581099.node2', '--smp', '2', '--memory', '1024M', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc=1', '--abort-on-internal-error', '1', '--developer-mode', 'true', '--default-log-level', 'info', '--collectd', 
'0', '--overprovisioned', '--prometheus-address', '127.0.61.2', '--unsafe-bypass-fsync', '1'] wait_other_notice=True wait_for_binary_proto=True
2021-02-16 11:13:16,060 24977   dtest                          DEBUG    | pushed_notifications_test.py:TestLocalhostPushedNotifications.restart_node_localhost_test - Test failed with errors: [(<pushed_notifications_test.TestLocalhostPushedNotifications testMethod=restart_node_localhost_test>, (<class 'ccmlib.node.Ti
meoutError'>, TimeoutError("16 Feb 2021 11:13:16 [node1] Missing: ['node is now in normal status|Starting listening for CQL clients']:\nScylla version 4.5.dev-0.20210215.495b7b559 with b.....\nSee system.log for remainder"), <traceback object at 0x7f116acbce60>))]
```
Failed due to https://github.com/scylladb/scylla-dtest/issues/1965
and with node1 failing to start (according to https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/745/artifact/logs-release.2/1613473996068_pushed_notifications_test.TestLocalhostPushedNotifications.restart_node_localhost_test/node1.log)
it is not running so we don't stop scylla_jmx.

Next time Cluster ID 72 is used:
```
2021-02-16 13:47:50,886 2315    dtest                          DEBUG    | secondary_indexes_test.py:TestSecondaryIndexes.test_remove_node_after_index_build - Test failed with errors: [(<secondary_indexes_test.TestSecondaryIndexes testMethod=test_remove_node_after_index_build>, (<class 'ccmlib.node.NodetoolError'>, NodetoolError("Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/495b7b5596ab5f2bd1f1149f5b56c0e550716f79/scylla-tools-java/bin/nodetool -h 127.0.72.1 -p 7172 flush' failed; exit status: 1; stdout: nodetool: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)\nSee 'nodetool help' or 'nodetool help <command>'.\n"), <traceback object at 0x7f116ab0e500>))]
```

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, if the node is not running for any reason,
failed to start, aborted, etc., do_stop does not
stop pscylla-jmx, which it should.

This change just ignores the node running status
and attempts to stop/kill all related processes that
appear to run.

Fixes #309

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
Test: https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/459/

**Comment by bhalevy** [comment]
@fruch ping

**Comment by bhalevy** [comment]
@fruch ping

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
