### PR TITLE
fix(scylla_node): covering cases when network_interfaces records could be None

### PR DESCRIPTION
**Pull request by dkropachev**
Since cassandra dropped thrift support it is possible that at some point ccm
can get request to deploy nodes/cluster with thrift_interface=None
which is currently results in python errors

### CODE REVIEW

**Comment by fruch** [comment]
@dkropachev can you expend a bit more, when this case is happening ? also take a look at integration test in github actions, it's failing (not sure if related or not)

**Comment by dkropachev** [comment]
> @dkropachev can you expend a bit more, when this case is happening ? also take a look at integration test in github actions, it's failing (not sure if related or not)

Example is auth tests:
https://github.com/scylladb/scylla-dtest/pull/1924/files

I work it around with following code in new_node:

```
    if cluster.__class__ in (Cluster, DseCluster):
        if cluster.cassandra_version() < '4':
            thrift = (ipformat % i, 9160)
    else:
        thrift = (ipformat % i, 9160)
```

**Comment by dkropachev** [comment]
> @dkropachev can you expend a bit more, when this case is happening ? also take a look at integration test in github actions, it's failing (not sure if related or not)

Checked intergration tests, did not hapen localy, don't know how to restart it.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> > @dkropachev can you expend a bit more, when this case is happening ? also take a look at integration test in github actions, it's failing (not sure if related or not)
> 
> Checked intergration tests, did not hapen localy, don't know how to restart it.

I think I've found the root cause, I wasn't caching correctly
https://github.com/scylladb/scylla-ccm/pull/304/commits/87bfe729d1870b6e123cc405c5fd8d3e72fdf6b1

**Pull request merged**
